import os       # for handling file paths
import sys      # for handling system-specific parameters and functions
from fastapi import FastAPI, HTTPException    # for creating API(API server) and handling HTTP exceptions(returns API errors)
from fastapi.middleware.cors import CORSMiddleware       # Allows frontend and backend to communicate.
from fastapi.staticfiles import StaticFiles     # for serving static files (like HTML, CSS, JS) from the backend.
from fastapi.responses import FileResponse      
from pydantic import BaseModel, HttpUrl     # Used for request validation
import uvicorn      # for running the FastAPI server

# Now, Adding the backend folder to the python path
sys.path.append(os.path.dirname(__file__))

# Now, importing the RAG chain components(modules)

from crawler import crawl_website       # websites crawler module
from embedder import embed_and_store, query_collection, get_chroma_collection    # embedding module
from chunker import chunk_pages      # Text chunking module
from chain import build_rag_chain, ask     # RAG chain building module
from embedder import (
    embed_and_store,
    query_collection,
    get_chroma_collection,
    query_with_threshold  # add this
)

# Now, crearing the FastAPI app
app = FastAPI(
    title="SitePilot API",
    description="RAG-powered chatbot for any website",
    version="1.0.0"
)

# Enabling CORS for frontend-backend communication

app.add_middleware(     # allows frontend requests.
    CORSMiddleware,
    allow_origins=["*"],        # allows requests from any origin(every website).(For production it would restrict this.)
    allow_credentials=True,     # allows cookies and authentication headers.
    allow_methods=["*"],        # allows all HTTP methods (GET, POST, etc.)
    allow_headers=["*"]     # allows all headers (like Content-Type, Authorization, etc.)
)

FRONTEND_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend")     # path to frontend folder

if os.path.exists(FRONTEND_DIR):
    app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")     # serves frontend files at root URL(accesible).


rag_chain = None
current_url = None

# Now, creating the Request models

class CrawlRequest(BaseModel):
    url: str        # URL to crawl
    max_pages: int = 10     # Maximum number of pages to crawl (default is 10)

class QuestionRequest(BaseModel):
    question: str        # User's question to ask the RAG system

# Now, creating the Response models

class CrawlResponse(BaseModel):
    success: bool       # Indicates if the crawl was successful
    message: str        # Message indicating the result of the crawl operation
    pages_crawled: int   # Number of pages that were crawled
    chunks_created: int    # Number of chunks that were created from the crawled pages
    url: str        # The URL that was crawled

class AnswerResponse(BaseModel):
    answer: str        # The answer generated by the RAG system
    sources: list[str]      # List of sources (chunks) that were used to generate the answer
    question: str      # The original question that was asked

# Now, creating the routes

@app.get("/")       # when the user visits, this fucntion runs.
async def serve_frontend():
    index_path = os.path.join(FRONTEND_DIR, "index.html")     # path to index.html file in frontend folder
    if os.path.exists(index_path):
        return FileResponse(index_path)       # serves the index.html file
    return {"message": "SitePilot API running", "status": "ok"}     # if index.html is not found, returns a simple JSON response.

@app.get("/health")     # health check endpoint, to check if the API is running(check backend status).
async def health_check():
    return {"status": "healthy", 
            "indexed_url": current_url,     # returns the health status and the currently indexed URL.
            "chain_ready": rag_chain is not None     # indicates if the RAG chain is ready to answer questions.
    }     

@app.post("/crawl")
async def crawl_endpoint(request: CrawlRequest):
    global rag_chain, current_url
    
    # URL validation
    if not request.url.startswith(("http://", "https://")):     # validates the URL format.
        raise HTTPException(status_code=400, detail="URL must start with http:// or https://.")

    try:
        # Step 1: Crawl the website
        print(f"\n[API] Crawling: {request.url}")
        pages = crawl_website(request.url, max_pages = request.max_pages)     # crawls the website and gets the pages.

        if not pages:
            raise HTTPException(status_code=422, detail="No pages could be crawled from this URL")     # if no pages are found, returns a 422 error.

        # Step 2: Chunk the pages
        print(f"[API] Chunking {len(pages)} pages...")
        chunks = chunk_pages(pages)      # chunks the crawled pages into smaller pieces.

        if not chunks:
            raise HTTPException(
                status_code=422,
                detail="No content could be extracted from crawled pages"
            )

        # Step 3: Embed and store in ChromaDB
        print(f"[API] Embedding {len(chunks)} chunks...")
        embed_and_store(chunks, collection_name="sitepilot")     # embeds the chunks and stores them in ChromaDB.

        # Step 4: Build RAG Chain
        print(f"[API] Building RAG chain...")
        rag_chain = build_rag_chain(collection_name="sitepilot")       # builds the RAG chain using the embedded chunks.
        current_url = request.url       # updates the currently indexed URL.

        return CrawlResponse(
            success=True,
            message=f"Successfully indexed {request.url}",
            pages_crawled=len(pages),
            chunks_created=len(chunks),
            url=request.url
        )
    except HTTPException:
        raise     # re-raises HTTP exceptions to be handled by FastAPI
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Crawling failed: {str(e)}")     # if any error occurs during crawling, it returns a 500 error with the error message.

@app.post("/ask", response_model=AnswerResponse)
async def ask_endpoint(request: QuestionRequest):
    global rag_chain

    if rag_chain is None:
        raise HTTPException(
            status_code=400,
            detail="No website indexed yet. Please crawl a website first."
        )

    if not request.question.strip():
        raise HTTPException(
            status_code=400,
            detail="Question cannot be empty."
        )

    try:
        # Step 1: Check retrieval confidence before calling LLM
        threshold_result = query_with_threshold(
            request.question,
            threshold=0.45
        )

        # Step 2: If no chunks meet threshold, return fallback immediately
        # This prevents the LLM from hallucinating on poor retrievals
        if not threshold_result["above_threshold"]:
            print(
                f"[Low confidence] max similarity: "
                f"{threshold_result['max_similarity']:.3f} "
                f"— skipping LLM"
            )
            return AnswerResponse(
                answer="I don't have information about that on this website.",
                sources=[],
                question=request.question
            )

        # Step 3: Confidence is acceptable, use full RAG chain
        print(
            f"[Good confidence] max similarity: "
            f"{threshold_result['max_similarity']:.3f} "
            f"— calling LLM"
        )
        response = ask(rag_chain, request.question)

        unique_sources = list(set(
            doc.metadata.get("source", "unknown")
            for doc in response["sources"]
        ))

        return AnswerResponse(
            answer=response["answer"],
            sources=unique_sources,
            question=request.question
        )

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to get answer: {str(e)}"
        )

@app.delete("/reset")
async def reset_endpoint():
    global rag_chain, current_url

    try:
        collection = get_chroma_collection("sitepilot")     # gets the ChromaDB collection.
        collection.delete(
            where = {"source": {"$ne": ""}}
        )      # deletes all data from the collection.

        rag_chain = None     # resets the RAG chain.
        current_url = None   # resets the currently indexed URL.

        return {"success": True, "message": "Index cleared successfully."}     # returns a success message.

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to reset index: {str(e)}")     # if any error occurs while resetting, it returns a 500 error with the error message.

if __name__ == "__main__":
    uvicorn.run(
        "main:app",      # points to the FastAPI app instance in this file.
        host="0.0.0.0",     # listens on all network interfaces, making it accessible from outside the container.
        port=8000,      # runs the server on port 8000.
        reload=True     # enables auto-reload for development (remove in production).
    )